# Generated by Django 2.2 on 2019-08-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190819_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', 'updated', 'timestamp']},
        ),
    ]
